Repository AllenSwiftClass/LottoDiary, pull requests merged in 2022-12, with the labels that each got.

#11 💄 CustomTabBar UI구현
  LottoDiary/LottoDiary.xcodeproj/project.pbxproj
  LottoDiary/LottoDiary/Sources/App/SceneDelegate.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListViewController.swift
  LottoDiary/LottoDiary/Sources/Present/HomeViewController.swift
  LottoDiary/LottoDiary/Sources/Present/LottoCalendarViewController.swift
  LottoDiary/LottoDiary/Sources/Present/LottoQRViewController.swift
  LottoDiary/LottoDiary/Sources/Present/RandomLottoNumberViewController.swift
  LottoDiary/LottoDiary/Sources/Present/TabBar/CustomTabBar.swift
  LottoDiary/LottoDiary/Sources/Present/TabBar/TabBarController.swift
Labels: 📙Sunny, 💄UI구현, Main Task

#13 💄 ChartLottoListView ui 구현
  LottoDiary/LottoDiary.xcodeproj/project.pbxproj
  LottoDiary/LottoDiary.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LottoDiary/LottoDiary/Resources/Assets.xcassets/happy.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/happy.imageset/happy.png
  LottoDiary/LottoDiary/Resources/Assets.xcassets/medal.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/medal.imageset/medal.png
  LottoDiary/LottoDiary/Resources/Assets.xcassets/trophy.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/trophy.imageset/trophy.png
  LottoDiary/LottoDiary/Sources/App/AppDelegate.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/ChartLottoListViewController.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/LottoList/LottoListCell.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/LottoList/LottoListDataSourceController.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/LottoList/LottoListHeader.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/Model/ChartModel.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/ViewModel/ChartViewModel.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/ViewModel/LottoListViewModel.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListViewController.swift
  LottoDiary/LottoDiary/Sources/Present/TabBar/TabBarController.swift
  LottoDiary/LottoDiary/Sources/Utility/Extensions/Int+.swift
Labels: 📙Sunny, 💄UI구현, Main Task

#12 💄 LottoCalendarView UI 구현
  LottoDiary/LottoDiary.xcodeproj/project.pbxproj
  LottoDiary/LottoDiary.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LottoDiary/LottoDiary/Resources/Assets.xcassets/add.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/add.imageset/plus.png
  LottoDiary/LottoDiary/Resources/Assets.xcassets/lotto.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/lotto.imageset/money.png
  LottoDiary/LottoDiary/Resources/Assets.xcassets/spitto.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/spitto.imageset/icons8-average-price-48.png
  LottoDiary/LottoDiary/Resources/Colors.xcassets/gray17181D.colorset/Contents.json
  LottoDiary/LottoDiary/Resources/Colors.xcassets/gray3C3C47.colorset/Contents.json
  LottoDiary/LottoDiary/Resources/Colors.xcassets/gray4D4D59.colorset/Contents.json
  LottoDiary/LottoDiary/Resources/Colors.xcassets/gray63626B.colorset/Contents.json
  LottoDiary/LottoDiary/Resources/Colors.xcassets/grayA09FA7.colorset/Contents.json
  LottoDiary/LottoDiary/Resources/Colors.xcassets/whiteEAE9EE.colorset/Contents.json
  LottoDiary/LottoDiary/Sources/DesignSystem/Color/Palette.swift
  LottoDiary/LottoDiary/Sources/DesignSystem/Font/Font.swift
  LottoDiary/LottoDiary/Sources/DesignSystem/Label/CustomLabel.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Type/Lotto.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/AddLottoViewController.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/LottoCalendarViewController.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/LottoCalenderViewController+DataSource.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/ViewModel/LottoCalendarViewModel.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/AddLottoFooterView.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/CustomTextField.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/DateHeaderView.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/ExpandButton.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/LottoCalendar.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/LottoCell.swift
  LottoDiary/LottoDiary/Sources/Present/LottoCalendarViewController.swift
  LottoDiary/LottoDiary/Sources/Present/TabBar/CustomTabBar.swift
  LottoDiary/LottoDiary/Sources/Present/TabBar/TabBarController.swift
  LottoDiary/LottoDiary/Sources/Present/ViewController2.swift
  LottoDiary/LottoDiary/Sources/Present/ViewController3.swift
  LottoDiary/LottoDiary/Sources/Utility/Extensions/String+.swift
Labels: 📘Brody, ✨기능 추가, 💄UI구현, Main Task

#17 ✨로또번호 랜덤으로 뽑아주는 뷰 구현
  LottoDiary/LottoDiary.xcodeproj/project.pbxproj
  LottoDiary/LottoDiary.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LottoDiary/LottoDiary/Resources/Assets.xcassets/PlusButton.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/PlusButton.imageset/PlusButton.png
  LottoDiary/LottoDiary/Resources/Assets.xcassets/add.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/add.imageset/plus.png
  LottoDiary/LottoDiary/Resources/Assets.xcassets/happy.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/happy.imageset/happy.png
  LottoDiary/LottoDiary/Resources/Assets.xcassets/lotto.imageset/money.png
  LottoDiary/LottoDiary/Resources/Assets.xcassets/medal.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/medal.imageset/medal.png
  LottoDiary/LottoDiary/Resources/Assets.xcassets/spitto.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/spitto.imageset/icons8-average-price-48.png
  LottoDiary/LottoDiary/Resources/Assets.xcassets/trophy.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/trophy.imageset/trophy.png
  LottoDiary/LottoDiary/Resources/Colors.xcassets/gray17181D.colorset/Contents.json
  LottoDiary/LottoDiary/Resources/Colors.xcassets/gray25262E.colorset/Contents.json
  LottoDiary/LottoDiary/Resources/Colors.xcassets/gray3C3C47.colorset/Contents.json
  LottoDiary/LottoDiary/Resources/Colors.xcassets/gray4D4D59.colorset/Contents.json
  LottoDiary/LottoDiary/Resources/Colors.xcassets/grayA09FA7.colorset/Contents.json
  LottoDiary/LottoDiary/Resources/Colors.xcassets/mainYellow.colorset/Contents.json
  LottoDiary/LottoDiary/Resources/Colors.xcassets/whiteEAE9EE.colorset/Contents.json
  LottoDiary/LottoDiary/Sources/App/AppDelegate.swift
  LottoDiary/LottoDiary/Sources/DesignSystem/Color/Palette.swift
  LottoDiary/LottoDiary/Sources/DesignSystem/Font/Font.swift
  LottoDiary/LottoDiary/Sources/DesignSystem/Label/CustomLabel.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Type/Lotto.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/AddLottoViewController.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/LottoCalendarViewController.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/LottoCalenderViewController+DataSource.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/ViewModel/LottoCalendarViewModel.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/AddLottoFooterView.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/CustomTextField.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/DateHeaderView.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/ExpandButton.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/LottoCalendar.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/Views/LottoCell.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/ChartLottoListViewController.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/LottoList/LottoListCell.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/LottoList/LottoListDataSourceController.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/LottoList/LottoListHeader.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/Model/ChartModel.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/ViewModel/ChartViewModel.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListView/ViewModel/LottoListViewModel.swift
  LottoDiary/LottoDiary/Sources/Present/ChartLottoListViewController.swift
  LottoDiary/LottoDiary/Sources/Present/LottoCalendarViewController.swift
  LottoDiary/LottoDiary/Sources/Present/NumberDrawTap/Models/LottoData.swift
  LottoDiary/LottoDiary/Sources/Present/NumberDrawTap/NumberDrawViewController.swift
  LottoDiary/LottoDiary/Sources/Present/NumberDrawTap/Views/LastLottoNumberTableViewCell.swift
  LottoDiary/LottoDiary/Sources/Present/NumberDrawTap/Views/LottoBall.swift
  LottoDiary/LottoDiary/Sources/Present/NumberDrawTap/Views/LottoNumbersView.swift
  LottoDiary/LottoDiary/Sources/Present/TabBar/CustomTabBar.swift
  LottoDiary/LottoDiary/Sources/Present/TabBar/TabBarController.swift
  LottoDiary/LottoDiary/Sources/Present/ViewController2.swift
  LottoDiary/LottoDiary/Sources/Present/ViewController3.swift
  LottoDiary/LottoDiary/Sources/Utility/Extensions/Int+.swift
  LottoDiary/LottoDiary/Sources/Utility/Extensions/String+.swift
  LottoDiary/LottoDiary/Sources/Utility/Extensions/UIView+.swift
Labels: 📕Youth, 💄UI구현, Main Task, Sub Task

#24 💄MainHomeView 구현
  LottoDiary/LottoDiary.xcodeproj/project.pbxproj
  LottoDiary/LottoDiary/Resources/Assets.xcassets/PlusButton.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/PlusButton.imageset/PlusButton.png
  LottoDiary/LottoDiary/Resources/Assets.xcassets/gokbob.imageset/Contents.json
  LottoDiary/LottoDiary/Resources/Assets.xcassets/gokbob.imageset/gokbob.png
  LottoDiary/LottoDiary/Resources/Colors.xcassets/mainYellow.colorset/Contents.json
  LottoDiary/LottoDiary/Sources/Present/Home/HomeViewController.swift
  LottoDiary/LottoDiary/Sources/Present/Home/InfoView.swift
  LottoDiary/LottoDiary/Sources/Present/Home/Models/DummyUser.swift
  LottoDiary/LottoDiary/Sources/Present/HomeViewController.swift
  LottoDiary/LottoDiary/Sources/Present/NumberDraw/Views/LottoBall.swift
  LottoDiary/LottoDiary/Sources/Utility/Extensions/String+.swift
Labels: 📕Youth, 💄UI구현, Main Task

#26 💄 나의 정보를 설정하는 UI 구현 (최신)
  LottoDiary/LottoDiary.xcodeproj/project.pbxproj
  LottoDiary/LottoDiary/Resources/Colors.xcassets/grayD8D8D8.colorset/Contents.json
  LottoDiary/LottoDiary/Sources/App/SceneDelegate.swift
  LottoDiary/LottoDiary/Sources/DesignSystem/Color/Palette.swift
  LottoDiary/LottoDiary/Sources/DesignSystem/Font/Font.swift
  LottoDiary/LottoDiary/Sources/DesignSystem/TexfField/CustomTextField.swift
  LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/AddLottoViewController.swift
  LottoDiary/LottoDiary/Sources/Present/MyInfomationSetting/myInfomationSettingViewController.swift
  LottoDiary/LottoDiary/Sources/Present/TabBar/TabBarController.swift
  LottoDiary/LottoDiary/Sources/Utility/Validation/Validation.swift
Labels: 📘Brody, ✨기능 추가, 💄UI구현, Main Task, Sub Task

#19 💄 IntroView UI구현
  LottoDiary/LottoDiary.xcodeproj/project.pbxproj
  LottoDiary/LottoDiary/Sources/App/SceneDelegate.swift
  LottoDiary/LottoDiary/Sources/Present/IntroViewController.swift
Labels: 📙Sunny, 💄UI구현, Main Task
